/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsNumber,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import { Type } from "class-transformer";
import { TransactionCreateNestedManyWithoutAdsInput } from "./TransactionCreateNestedManyWithoutAdsInput";
import { MessageCreateNestedManyWithoutAdsInput } from "./MessageCreateNestedManyWithoutAdsInput";
import { ReviewCreateNestedManyWithoutAdsInput } from "./ReviewCreateNestedManyWithoutAdsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class AdCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  status?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  photos?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  videos?: string | null;

  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TransactionCreateNestedManyWithoutAdsInput,
  })
  @ValidateNested()
  @Type(() => TransactionCreateNestedManyWithoutAdsInput)
  @IsOptional()
  @Field(() => TransactionCreateNestedManyWithoutAdsInput, {
    nullable: true,
  })
  transactions?: TransactionCreateNestedManyWithoutAdsInput;

  @ApiProperty({
    required: false,
    type: () => MessageCreateNestedManyWithoutAdsInput,
  })
  @ValidateNested()
  @Type(() => MessageCreateNestedManyWithoutAdsInput)
  @IsOptional()
  @Field(() => MessageCreateNestedManyWithoutAdsInput, {
    nullable: true,
  })
  messages?: MessageCreateNestedManyWithoutAdsInput;

  @ApiProperty({
    required: false,
    type: () => ReviewCreateNestedManyWithoutAdsInput,
  })
  @ValidateNested()
  @Type(() => ReviewCreateNestedManyWithoutAdsInput)
  @IsOptional()
  @Field(() => ReviewCreateNestedManyWithoutAdsInput, {
    nullable: true,
  })
  reviews?: ReviewCreateNestedManyWithoutAdsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { AdCreateInput as AdCreateInput };
