/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsNumber,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import { Type } from "class-transformer";
import { TransactionUpdateManyWithoutAdsInput } from "./TransactionUpdateManyWithoutAdsInput";
import { MessageUpdateManyWithoutAdsInput } from "./MessageUpdateManyWithoutAdsInput";
import { ReviewUpdateManyWithoutAdsInput } from "./ReviewUpdateManyWithoutAdsInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class AdUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  title?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  price?: number | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  status?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  photos?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  videos?: string | null;

  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => TransactionUpdateManyWithoutAdsInput,
  })
  @ValidateNested()
  @Type(() => TransactionUpdateManyWithoutAdsInput)
  @IsOptional()
  @Field(() => TransactionUpdateManyWithoutAdsInput, {
    nullable: true,
  })
  transactions?: TransactionUpdateManyWithoutAdsInput;

  @ApiProperty({
    required: false,
    type: () => MessageUpdateManyWithoutAdsInput,
  })
  @ValidateNested()
  @Type(() => MessageUpdateManyWithoutAdsInput)
  @IsOptional()
  @Field(() => MessageUpdateManyWithoutAdsInput, {
    nullable: true,
  })
  messages?: MessageUpdateManyWithoutAdsInput;

  @ApiProperty({
    required: false,
    type: () => ReviewUpdateManyWithoutAdsInput,
  })
  @ValidateNested()
  @Type(() => ReviewUpdateManyWithoutAdsInput)
  @IsOptional()
  @Field(() => ReviewUpdateManyWithoutAdsInput, {
    nullable: true,
  })
  reviews?: ReviewUpdateManyWithoutAdsInput;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;
}

export { AdUpdateInput as AdUpdateInput };
